### ISSUE TITLE
Option to render first page twice

### ISSUE THREAD

**Issue by ksmithut** [blakeembrey/metalsmith-collections-paginate#2]
What if there was also an option to render the first page a second time, using both the `options.first` and `options.path`? That way, you could have `/posts/` and `/posts/1/` show the same content. For SEO you could set the canonical, but the url structure becomes more verbose, in case anyone were to manually put that 1 in there.

**Comment by blakeembrey** [comment]
Hmm, I was thinking about that too when I wrote it. I think the primary reason I didn't do that was that previous is a reference. Maybe previous always linked to the manual override?

**Comment by ksmithut** [comment]
I like it linking to the manual override. The additional page would just be for those (like me) who sometimes navigate paginated pages via the url... call me crazy

**Comment by blakeembrey** [comment]
Ok, released with `v1.0.1`

**Comment by ksmithut** [comment]
Awesome! Thanks for your time today :)
