### ISSUE TITLE
Adjust this to support paginating any array

### ISSUE THREAD

**Issue by boushley** [blakeembrey/metalsmith-collections-paginate#4]
I currently have a use case where I want to paginate a list of authors.

The authors are on the metalsmith site metadata. I would have to convert them into a collection to use this plugin, and I'm hoping to avoid doing that (since it isn't really a collection of files).

Would you be open to a PR that changes this to check for the collection in `metadata.collections[name]` but if that doesn't exist it could fall back to `metadata[name]` and check if it is an array.

The rest of the code would remain unchanged, and then you could paginate any list that is in the metadata.

**Comment by blakeembrey** [comment]
Maybe add a flag for it? `collection: false`? However, this does change the original intention of the module somewhat. And makes it impossible to do both at once. Maybe we need to create a new module based on this one that works on any data?

**Comment by boushley** [comment]
I was considering making a new module, but since they would be identical except for a single line I feel gross making an entirely new module.

**Comment by boushley** [comment]
Also, I could add a `collection: false` on a per collection/definition basis. We would just move the retrieval of `pageOpts` on line 35 up to the top of the iteration over the keys.

If you're happy to have a `collection: false` piece of metadata then I can do it on a per collection basis.

**Comment by blakeembrey** [comment]
@boushley How about a refactor that'll keep this compatible in the future? We could move all the logic into a common `pagination-metalsmith-array` module, then use that to create two new modules for collections and generic middleware. Thoughts?

**Comment by boushley** [comment]
I'm thinking it would probably make the most sense to just adjust the way this works a bit more.

I can make a function that looks up arrays based on dot syntax being provided as the key in the options object. So you would write something like this:

```
paginate({
    "collections.articles": { ... },
    "authors": { ... }
})
```

And then for backwards compatibility we could first perform this lookup on the collections object, and if we find it there then we can print a deprecation message.

If we make this change though, this package becomes more `metalsmith-paginate` not really `metalsmith-collections-paginate`.

@blakeembrey Thoughts?

**Comment by blakeembrey** [comment]
I think that works great. I'd be interested in creating a new package based on that, then I can make sure this one just works based on top of that and we have no compatibility issues. I can make that today, what do you think?

**Comment by boushley** [comment]
Sure, sounds good. If you want me to build out the other package let me know.

**Comment by blakeembrey** [comment]
@boushley Want to check out https://github.com/blakeembrey/metalsmith-pagination and let me know what you think?

**Comment by boushley** [comment]
That looks great.

I had been looking for something like `to-function` but couldn't figure out what it was called!

**Comment by blakeembrey** [comment]
Sweet, there's some minor compatibility issues since I can't just automatically generate `name` and stuff from the collection key, but everything else should look the same. I'll close this now.
