### ISSUE TITLE
Adding previous and next links within a post

### ISSUE THREAD

**Issue by edwardessing** [blakeembrey/metalsmith-collections-paginate#6]
I currently have my posts collection nicely paginated. However I was wondering if there was a simple method for finding the next and previous (post) links within and for that particular post page. The metalsmith-collections plugin lists "adds next and previous references to each file in the collection" as one of its features however the documentation doesn't really expand on it. Thanks.

**Comment by blakeembrey** [comment]
@edwardessing The files aren't being mutated in any way here. If you're using `metalsmith-collections` though, you can use the `next` and `previous` references (which are just `next` and `previous`) to handle that.

Edit: What part are you currently stuck on? Is it in the template or somewhere else?

**Comment by edwardessing** [comment]
Thanks for the pointer, I've got it working now. I'm foremost a designer, so unless the documentation is very, very dumbed down and clear I'm at a loss (:

**Comment by blakeembrey** [comment]
I completely understand, it wasn't too clear - I checked the code to make sure it was like that. I'd open an issue over at `metalsmith-collections` on that.

**Comment by edwardessing** [comment]
Yeah, I had a feeling that would've been more appropriate...but then I noticed this plugin was more active.
